//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personalsystem.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Interviews
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string ApplicantId { get; set; }
        public string InterviewerId { get; set; }
        public Nullable<int> Application_Id { get; set; }
    
        public virtual Applications Applications { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual AspNetUsers AspNetUsers1 { get; set; }
    }
}
