//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personalsystem.Diagrams
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Companies> Companies { get; set; }
        public virtual DbSet<DepartmentGroups> DepartmentGroups { get; set; }
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<Interviews> Interviews { get; set; }
        public virtual DbSet<NewsItems> NewsItems { get; set; }
        public virtual DbSet<ScheduleItems> ScheduleItems { get; set; }
        public virtual DbSet<Schedules> Schedules { get; set; }
        public virtual DbSet<Vacancies> Vacancies { get; set; }
    }
}
