//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personalsystem.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedules
    {
        public Schedules()
        {
            this.AspNetUsers = new HashSet<AspNetUsers>();
        }
    
        public int Id { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public int DepartmentId { get; set; }
        public int GroupId { get; set; }
    
        public virtual ICollection<AspNetUsers> AspNetUsers { get; set; }
        public virtual DepartmentGroups DepartmentGroups { get; set; }
        public virtual Departments Departments { get; set; }
    }
}
