//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personalsystem.Diagrams
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacancies
    {
        public Vacancies()
        {
            this.Applications = new HashSet<Applications>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public System.DateTime Created { get; set; }
        public int CompanyId { get; set; }
        public string CreatorId { get; set; }
    
        public virtual ICollection<Applications> Applications { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Companies Companies { get; set; }
    }
}
